version: '3.0'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/${APP_NAME}
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - "8094:80"
    networks:
      tour_net:
        ipv4_address: 173.31.1.1
    depends_on:
      - php-fpm
      - db

  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        user: zloradnij
        uid: 1000
        workDir: ${APP_NAME}
    volumes:
      - ./:/${APP_NAME}
    container_name: ${PROJECT_NAME}-php
    networks:
      tour_net:
        ipv4_address: 173.31.1.2
    depends_on:
      - db

  db:
    build:
      context: ./docker/db
    container_name: ${PROJECT_NAME}-db
    volumes:
      - tour-pg:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - '5438:5432'
    expose:
      - "5438"
    networks:
      tour_net:
        ipv4_address: 173.31.1.3

networks:
  tour_net:
    ipam:
      driver: default
      config:
        - subnet: 173.31.0.0/16

volumes:
  tour-pg:
